### ISSUE TITLE
MSVC config

### ISSUE THREAD

**Issue by Sp3EdeR** [taocpp/sequences#1]
Hello!

config.hpp contains the line "#elif defined( _MSC_VER ) && ( _MSC_VER >= 190023918 )".
The _MSC_VER macro is defined as:
* VS 2013: 1800
* VS 2015: 1900
* VS 2017: 1910

I believe that that line should be modified as such (unless a VS2015 update package existence should be checked):
#elif defined( _MSC_VER ) && ( _MSC_VER >= 1900 )

THere is issue with the __cplusplus value for VS, since it is defined to 199711L even in VS2017. This causes the above line not to execute at all on VS.

**Comment by d-frey** [comment]
I should probably change `_MSC_VER` to `_MSC_FULL_VER`, but I will have some more maintenance to do on this repo anyways, which I hope I'll find some time for in the near future.

**Comment by d-frey** [comment]
This is fixed now.
